name: Deploy OEVP-Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy OEVP-Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm install
          npm run build

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H ssh.ocf.berkeley.edu >> ~/.ssh/known_hosts

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ssh.ocf.berkeley.edu
          username: asucevp
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd OEVP-site
            git pull
            cp -r out/* ../public_html
